import { useNavigate } from 'react-router-dom'
import { NavBar } from '../components/ui'

const serif = { fontFamily: 'Georgia, "Times New Roman", serif' }
const sans = { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }

function Section({ title, children }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
      <div style={{ ...serif, fontSize: 15, color: '#e8e4dc' }}>{title}</div>
      <div style={{ fontSize: 13, color: '#999', ...sans, lineHeight: 1.7 }}>{children}</div>
    </div>
  )
}

export default function Terms() {
  const navigate = useNavigate()
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <NavBar title="Terms of Service" onBack={() => navigate(-1)} />
      <div style={{ flex: 1, overflowY: 'auto', padding: '16px', display: 'flex', flexDirection: 'column', gap: 20 }}>
        <div style={{ fontSize: 11, color: '#555', ...sans }}>Last updated: July 2026</div>

        <Section title="What Stackd is">
          Stackd is a review and ranking app for energy drinks, protein bars, and supplements. You can rate products, write reviews, build ranked lists, and see what the community thinks -- plus an
          AI-generated read on ingredient quality for products that have one.
        </Section>

        <Section title="Age requirement">
          Many products reviewed here are high in caffeine and aren't recommended for minors. By creating an account, you're confirming you're old enough to use this app in your jurisdiction.
        </Section>

        <Section title="Your content">
          Reviews, ratings, lists, and profile info you post are yours. By posting them, you give Stackd a license to display them within the app (e.g. showing your review on a product page, or your
          ranked list to people you share it with). You're responsible for what you post -- don't post anything false, defamatory, or that you don't have the right to share.
        </Section>

        <Section title="Community conduct">
          No fake reviews, spam, harassment, or abuse of the reporting system. Reviews can be reported by other users and are reviewed manually; we may remove content or limit accounts that violate
          this. Simple rate limits apply to reviews, product submissions, and reports to deter single-actor abuse.
        </Section>

        <Section title="AI-generated content">
          Ingredient quality scores and summaries are generated by an AI model reading a product's ingredient list. They're an estimate of ingredient quality only -- not medical, nutritional, or
          professional advice, and not a substitute for reading the actual label or talking to a doctor or dietitian.
        </Section>

        <Section title="No warranty">
          Stackd is provided "as is." We don't guarantee the accuracy of user-submitted product data, AI-generated scores, or that the service will be uninterrupted or error-free.
        </Section>

        <Section title="Account termination">You can delete your account at any time from your profile. We may suspend or terminate accounts that violate these terms.</Section>

        <Section title="Changes">We may update these terms as the app evolves. Continued use after a change means you accept the update.</Section>

        <Section title="Contact">Questions about these terms? Reach out to the app's operator directly.</Section>
      </div>
    </div>
  )
}
